### ISSUE TITLE
Super cool

### ISSUE THREAD

**Issue by azat-co** [msmfsd/react-quickly-code-es6#1]
many thanks!
Do you think I should include ES6 in each chapter by having ES5 and ES6 examples or just have one chapter for ES6 in the middle or end of the book? (Right now it's one chapter.)

**Comment by msmfsd** [comment]
Firstly thanks for the book, I had just completed some other manning MEAP books and really wanted to dive into react past the beginner level and your book was fantastic and I am using the knowledge every day.

I think having both would be good, that way you can easily drop all the ES5 examples later on if you want to. I really think it is important to push people learning JS towards ES6/7 as much as possible to improve the coding experience for all developers - and new versions of react and a lot of tutorials and guides are all focussed on ES6 too.
